In [1]:
import pandas as pd

In [2]:
data = [
    "When life gives you lemons, make lemonade! ",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon - there's a great sale today.",
    "Does Maven Market carry Eureka lemons or Meyer lemons?",
    "An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",
    "iced tea is my favorite"
]

In [3]:
pd.set_option('display.max_colwidth' ,None )

In [4]:
df = pd.DataFrame(data , columns = ['sentence'])

In [5]:
df

                                                                  sentence
0                              When life gives you lemons, make lemonade!
1                              She bought 2 lemons for $1 at Maven Market.
2              A dozen lemons will make a gallon of lemonade. [AllRecipes]
3                               lemon, lemon, lemons, lemon, lemon, lemons
4  He's running to the market to get a lemon - there's a great sale today.
5                   Does Maven Market carry Eureka lemons or Meyer lemons?
6            An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]
7                                                  iced tea is my favorite

In [6]:
df['sentence']= df['sentence'].str.lower()

In [7]:
df['sentence']

0                                when life gives you lemons, make lemonade!
1                                she bought 2 lemons for $1 at maven market.
2                a dozen lemons will make a gallon of lemonade. [allrecipes]
3                                 lemon, lemon, lemons, lemon, lemon, lemons
4    he's running to the market to get a lemon - there's a great sale today.
5                     does maven market carry eureka lemons or meyer lemons?
6              an arnold palmer is half lemonade, half iced tea. [wikipedia]
7                                                    iced tea is my favorite
Name: sentence, dtype: str

In [8]:
df["sentence_clean"] = df["sentence"].str.replace(r'\[.*?\]','', regex = True)

In [9]:
df["sentence_clean"]

0                                when life gives you lemons, make lemonade!
1                                she bought 2 lemons for $1 at maven market.
2                            a dozen lemons will make a gallon of lemonade.
3                                 lemon, lemon, lemons, lemon, lemon, lemons
4    he's running to the market to get a lemon - there's a great sale today.
5                     does maven market carry eureka lemons or meyer lemons?
6                         an arnold palmer is half lemonade, half iced tea.
7                                                    iced tea is my favorite
Name: sentence_clean, dtype: str

In [10]:
df["sentence_clean"] = df["sentence_clean"].str.replace(r'[^\w\s]','', regex = True)

In [11]:
df["sentence_clean"]

0                              when life gives you lemons make lemonade
1                              she bought 2 lemons for 1 at maven market
2                         a dozen lemons will make a gallon of lemonade
3                                  lemon lemon lemons lemon lemon lemons
4    hes running to the market to get a lemon  theres a great sale today
5                  does maven market carry eureka lemons or meyer lemons
6                       an arnold palmer is half lemonade half iced tea
7                                                iced tea is my favorite
Name: sentence_clean, dtype: str

In [12]:
# Lets create a function to clean data at once
def lower_nd_replace(series):
    output = series.str.lower()                                # converting to lower
    output = series.str.replace(r'\[.*?\]','', regex = True)   # removed brackets and data inside it
    output = series.str.replace(r'[^\w\s]','', regex = True)   # removed all punctuations
    return output

In [13]:
df["sentence_clean_new"] = lower_nd_replace(df['sentence'])

In [14]:
df["sentence_clean_new"]

0                              when life gives you lemons make lemonade
1                              she bought 2 lemons for 1 at maven market
2               a dozen lemons will make a gallon of lemonade allrecipes
3                                  lemon lemon lemons lemon lemon lemons
4    hes running to the market to get a lemon  theres a great sale today
5                  does maven market carry eureka lemons or meyer lemons
6              an arnold palmer is half lemonade half iced tea wikipedia
7                                                iced tea is my favorite
Name: sentence_clean_new, dtype: str

In [15]:
# ------------------ spaCy---------------------------

# WHen you import spaCy , you need to specify which language to use. 
# In this case we are choosing English, which includes information from a large amount of annotated text

# If directly not loading english language try below step
# !python -m spacy download en_core_web_sm
# !pip install spacy

import spacy
nlp = spacy.load('en_core_web_sm')

In [16]:
sentence = "i'm selling lemons for $5 today"
doc = nlp(sentence)

In [17]:
doc
# print(type(doc))

i'm selling lemons for $5 today

In [18]:
'''
1.Tokenization:
    - Tokenization lets you break text up into smaller units, like words.
    - Generally text strings are often split by whitespace to make tokens.
'''

tokens = []
for token in doc:
    tokens.append(token.text)
print(tokens)  
# [i,',m, selling ,lemons ,for ,$,5, today]

# or

# tokens = [token.text for token in doc]
# print(tokens)

['i', "'m", 'selling', 'lemons', 'for', '$', '5', 'today']

In [19]:
# a = "i'm selling lemons for $5 today"
# tokens = []
# for token in a:
#     tokens.append(token)
# print(tokens)

In [20]:
'''
Lemmatization:
    - It reduces words to their base form.
    - spaCy uses combination of linguistic rules and stats models to lemmatize text.
    e.g running => run

There is alternative for lemmatization i.e stemming.

whats Difference between lemmatization and stemming ?

They both reduce words to their base form but lemmatization is the smarter way to approach 
and generally perform better.

   stemming -> am => am,is => is , are=> ar, happy => happi, happiness => happi
   Lemmatization -> am => be,is => be , are=> be, happy => happy, happiness => happy
'''


# token.lemma_ => Gives lemmatization for token
# ['I', 'be', 'sell', 'lemon', 'for', '$', '5', 'today']
# Here in this case 'i' gets converted into 'I', "'m" gets conevrted to 'be' i.e to base form
# lemmatised_words = []

# for token in doc:
#     lemmatised_words.append(token.lemma_)

# print(lemmatised_words)


lemmatised_words = [token.lemma_ for token in doc]
print(lemmatised_words)
# "i'm selling lemons for $5 today"

['I', 'be', 'sell', 'lemon', 'for', '$', '5', 'today']

In [21]:
'''
Stop words Removal:
    They are words without any significant meaning.
    To check list of stopwords => print(nlp.Defaults.stop_words)
    Stop words are common words that appear very frequently in a language,
    but carry little meaningful information for many NLP tasks.
'''

filtered_words = []

for word in lemmatised_words:
    token = nlp(word)[0]   # convert word to spaCy token
    if not token.is_stop:
        filtered_words.append(word)

print(filtered_words)
# ['I', 'be', 'sell', 'lemon', 'for', '$', '5', 'today']

['sell', 'lemon', '$', '5', 'today']

In [22]:
print(len(nlp.Defaults.stop_words))

326

In [23]:
'''
POS => Part Of Speech Tagging
    - It lets you label nouns, verbs, Adjective etc within text data
    - Identifying the grammatical role of each word in a sentence.
    - This is optional but sometimes used as a filtering technique to only look at nouns and pronouns for analysis
    
| Tag (token.pos_)  | Meaning      |
| ----              | ------------ |
| NOUN              | Person/thing |
| VERB              | Action       |
| ADJ               | Description  |
| ADV               | How/when     |
| PRON              | Pronoun      |
| ADP               | Preposition  |
| DET               | Determiner   |
'''

for token in doc:
    print(token.text, "=>", token.pos_)

i => PRON
'm => AUX
selling => VERB
lemons => NOUN
for => ADP
$ => SYM
5 => NUM
today => NOUN

In [24]:
'''
NER => Named Entity Recognisation
    - It identifies and categorises important real-word entities
    - POS helps identify entities like:
        1. Person names
        2. Locations
        3. Organizations
        4. Date  etc.
        doc.ents   => entity/ word from sentence
        doc.label_ => label or category for entity
'''
# print(doc.ents)

for ent in doc.ents:
    print(ent.text, ent.label_)

5 MONEY
today DATE

In [25]:
# Lets create a function that will get a token , lemmas, removed stop word
import spacy
nlp = spacy.load('en_core_web_sm')
def token_lemma_remove_stopwords(text):
    doc = nlp(text)
    filtered_words = []
    
    for word in lemmatised_words:
        token = nlp(word)[0]   # convert word to spaCy token
        if not token.is_stop:
            filtered_words.append(word)
        
    output = " ".join(filtered_words)
    return output

In [26]:
clean_sentence = token_lemma_remove_stopwords("i'm selling lemons for $5 today")
print(clean_sentence)

sell lemon $ 5 today

In [27]:
# Filter by POS
def filter_pos(text, pos_list = ["NOUN","PROPN"]):
    doc = nlp(text)
    
    output = []

    for token in doc:
        if token.pos_ in pos_list:
            output.append(token.text)      # returns the nouns and pronouns
    
    output = " ".join(output)
    return output

In [28]:
pos_tags = filter_pos("i'm selling lemons for $5 today")
pos_tags

'lemons today'

In [29]:

# Function to make sentence lower and clean it.
def lower_nd_replace(series):
    output = series.str.lower()
    output = output.str.replace(r'\[.*?\]', '', regex=True)
    output = output.str.replace(r'[^\w\s]', '', regex=True)
    return output


# Lets create a function that will get a token , lemmas, removed stop word
import spacy
nlp = spacy.load('en_core_web_sm')
def token_lemma_remove_stopwords(text):
    doc = nlp(text)
    filtered_words = []
    lemmatised_words = [token.lemma_ for token in doc]
    for word in lemmatised_words:
        token = nlp(word)[0]   # convert word to spaCy token
        if not token.is_stop:
            filtered_words.append(word)
        
    output = " ".join(filtered_words)
    return output

# Filter by POS
def filter_pos(text, pos_list = ["NOUN","PROPN"]):
    doc = nlp(text)
    
    output = []

    for token in doc:
        if token.pos_ in pos_list:
            output.append(token.text)      # returns the nouns and pronouns
    
    output = " ".join(output)
    return output

In [30]:
# Creating pipeline for NLP task
def nlp_pipeline(series):
    output = lower_nd_replace(series)
    output = output.apply(token_lemma_remove_stopwords)
    output = output.apply(filter_pos)
    return output

In [31]:
import pandas as pd

data1 = [
    "When life gives you lemons, make lemonade! ",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon - there's a great sale today.",
    "Does Maven Market carry Eureka lemons or Meyer lemons?",
    "An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",
    "iced tea is my favorite"
]

# Turn all sentences into Data Frame

df = pd.DataFrame(data1 , columns = ['sentence'])

df['new_sentence'] = nlp_pipeline(df['sentence'])
df

,sentence,new_sentence
0,"When life gives you lemons, make lemonade!",life lemon lemonade
1,She bought 2 lemons for $1 at Maven Market.,lemon maven market
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],dozen lemon gallon lemonade
3,"lemon, lemon, lemons, lemon, lemon, lemons",lemon lemon lemon lemon lemon lemon
4,He's running to the market to get a lemon - there's a great sale today.,s market lemon sale today
5,Does Maven Market carry Eureka lemons or Meyer lemons?,maven market eureka lemon lemon
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",palmer lemonade half ice tea
7,iced tea is my favorite,ice tea favorite