In [1]:
import pandas as pd

In [2]:
# Function to make sentence lower and clean it.
def lower_nd_replace(series):
    output = series.str.lower()
    output = output.str.replace(r'\[.*?\]', '', regex=True)
    output = output.str.replace(r'[^\w\s]', '', regex=True)
    return output


# Lets create a function that will get a token , lemmas, removed stop word
import spacy
nlp = spacy.load('en_core_web_sm')
def token_lemma_remove_stopwords(text):
    doc = nlp(text)
    filtered_words = []
    lemmatised_words = [token.lemma_ for token in doc]
    for word in lemmatised_words:
        token = nlp(word)[0]   # convert word to spaCy token
        if not token.is_stop:
            filtered_words.append(word)
        
    output = " ".join(filtered_words)
    return output

# Filter by POS
def filter_pos(text, pos_list = ["NOUN","PROPN"]):
    doc = nlp(text)
    
    output = []

    for token in doc:
        if token.pos_ in pos_list:
            output.append(token.text)      # returns the nouns and pronouns
    
    output = " ".join(output)
    return output


# Creating pipeline for NLP task
def nlp_pipeline(series):
    output = lower_nd_replace(series)
    output = output.apply(token_lemma_remove_stopwords)
    output = output.apply(filter_pos)
    return output

# from nlp_functions import nlp_pipeline

In [3]:
import pandas as pd
# from nlp_functions import nlp_pipeline

data = [
    "When life gives you lemons, make lemonade! ",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon - there's a great sale today.",
    "Does Maven Market carry Eureka lemons or Meyer lemons?",
    "An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",
    "iced tea is my favorite"
]
# Turn all sentences into Data Frame
df = pd.DataFrame(data , columns = ['sentence'])
df['sentence'] = nlp_pipeline(df['sentence'])
df

                              sentence
0                  life lemon lemonade
1                   lemon maven market
2          dozen lemon gallon lemonade
3  lemon lemon lemon lemon lemon lemon
4            s market lemon sale today
5      maven market eureka lemon lemon
6         palmer lemonade half ice tea
7                     ice tea favorite

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer(stop_words = 'english')
dtm = cv.fit_transform(df['sentence'])
# get all values for words
# dtm.toarray()
# get column names from count vectorizer
# columns = cv.get_feature_names_out()
# dtm_df = pd.DataFrame(data = dtm.toarray() , columns = cv.get_feature_names_out())

In [6]:
# dtm.toarray()
# columns = cv.get_feature_names_out()
dtm_df = pd.DataFrame(data = dtm.toarray() , columns = cv.get_feature_names_out())
dtm_df

,dozen,eureka,favorite,gallon,half,ice,lemon,lemonade,life,market,maven,palmer,sale,tea,today
0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0
1,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
2,1,0,0,1,0,0,1,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,1,0,0,1,0,1
5,0,1,0,0,0,0,2,0,0,1,1,0,0,0,0
6,0,0,0,0,1,1,0,1,0,0,0,1,0,1,0
7,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer()
tfidf = tv.fit_transform(df['sentence'])
# tfidf.toarray()
tfidf_df = pd.DataFrame(data = tfidf.toarray() , columns = tv.get_feature_names_out())
tfidf_df

,dozen,eureka,favorite,gallon,half,ice,lemon,lemonade,life,market,maven,palmer,sale,tea,today
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.375318,0.543168,0.75107,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.411442,0.000000,0.00000,0.595449,0.690041,0.000000,0.000000,0.000000,0.000000
2,0.600547,0.000000,0.000000,0.600547,0.000000,0.000000,0.300100,0.434311,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.300100,0.000000,0.00000,0.434311,0.000000,0.000000,0.600547,0.000000,0.600547
5,0.000000,0.556913,0.000000,0.000000,0.000000,0.000000,0.556591,0.000000,0.00000,0.402755,0.466736,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.504577,0.422875,0.000000,0.364907,0.00000,0.000000,0.000000,0.504577,0.000000,0.422875,0.000000
7,0.000000,0.000000,0.644859,0.000000,0.000000,0.540443,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.540443,0.000000